# Generated by Django 6.0.8 on 2026-09-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Software Development', 'Software Development'), ('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('AI Solutions', 'AI Solutions'), ('Cyber Security', 'Cyber Security'), ('Digital Marketing', 'Digital Marketing')], max_length=80)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
