# Generated by Django 6.0.8 on 2026-09-01 15:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catalog_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('own', 'Own Products'), ('partnership', 'Partnerships'), ('client', 'Client Projects')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.project_image_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='project',
            name='image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to=api.models.project_logo_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='related_image',
            field=models.ImageField(blank=True, upload_to=api.models.project_related_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='project',
            name='related_image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='related_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='related_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='accent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.slide_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='slide',
            name='image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='slide',
            name='primary_cta_href',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='slide',
            name='primary_cta_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='slide',
            name='secondary_cta_href',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='slide',
            name='secondary_cta_label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
