# Generated by Django 6.0.8 on 2026-09-01 16:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slide_project_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.service_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='service',
            name='image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department_productions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.team_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
