# Generated by Django 6.0.8 on 2026-09-01 16:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_team_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.testimonial_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
