# Generated by Django 6.0.8 on 2026-09-01 16:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_testimonial_faq_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='director_image',
            field=models.ImageField(blank=True, upload_to=api.models.department_director_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='department',
            name='director_image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='director_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ImageField(blank=True, upload_to=api.models.department_icon_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='department',
            name='icon_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='productions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.product_image_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='product',
            name='image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_image',
            field=models.ImageField(blank=True, upload_to=api.models.product_screen_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_image_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
