# Generated by Django 6.0.8 on 2026-09-01 16:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_department_cms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(blank=True, default=list)),
                ('about_eyebrow', models.CharField(blank=True, max_length=120)),
                ('about_title', models.CharField(blank=True, max_length=255)),
                ('about_highlight', models.CharField(blank=True, max_length=255)),
                ('about_body', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, upload_to=api.models.homepage_about_upload, validators=[api.models.validate_image_file])),
                ('about_image_fallback', models.CharField(blank=True, max_length=500)),
                ('about_cta_label', models.CharField(blank=True, max_length=120)),
                ('about_cta_href', models.CharField(blank=True, max_length=500)),
                ('about_badge_value', models.CharField(blank=True, max_length=80)),
                ('about_badge_label', models.CharField(blank=True, max_length=160)),
                ('about_highlights', models.JSONField(blank=True, default=list)),
                ('why_eyebrow', models.CharField(blank=True, max_length=120)),
                ('why_title', models.CharField(blank=True, max_length=255)),
                ('why_highlight', models.CharField(blank=True, max_length=255)),
                ('why_subtitle', models.TextField(blank=True)),
                ('why_image', models.ImageField(blank=True, upload_to=api.models.homepage_why_upload, validators=[api.models.validate_image_file])),
                ('why_image_fallback', models.CharField(blank=True, max_length=500)),
                ('why_items', models.JSONField(blank=True, default=list)),
                ('method_eyebrow', models.CharField(blank=True, max_length=120)),
                ('method_title', models.CharField(blank=True, max_length=255)),
                ('method_highlight', models.CharField(blank=True, max_length=255)),
                ('method_subtitle', models.TextField(blank=True)),
                ('method_steps', models.JSONField(blank=True, default=list)),
                ('expertise_eyebrow', models.CharField(blank=True, max_length=120)),
                ('expertise_title', models.CharField(blank=True, max_length=255)),
                ('expertise_highlight', models.CharField(blank=True, max_length=255)),
                ('expertise_subtitle', models.TextField(blank=True)),
                ('expertise_items', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'homepage content',
                'verbose_name_plural': 'homepage content',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, upload_to=api.models.client_logo_upload, validators=[api.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
