# Generated by Django 6.0.8 on 2026-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_media_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='service',
            field=models.CharField(max_length=80),
        ),
    ]
