from django.urls import path

from .auth_views import CsrfView, LoginView, LogoutView, MeView
from .cms_views import (
    AdminClientDetail,
    AdminClientListCreate,
    AdminDepartmentDetail,
    AdminDepartmentListCreate,
    AdminFAQDetail,
    AdminFAQListCreate,
    AdminHomepage,
    AdminMediaDetail,
    AdminMediaListCreate,
    AdminProductDetail,
    AdminProductListCreate,
    AdminProjectDetail,
    AdminProjectListCreate,
    AdminServiceDetail,
    AdminServiceListCreate,
    AdminSlideDetail,
    AdminSlideListCreate,
    AdminTeamMemberDetail,
    AdminTeamMemberListCreate,
    AdminTestimonialDetail,
    AdminTestimonialListCreate,
    PublicClientList,
    PublicDepartmentList,
    PublicFAQList,
    PublicHomepage,
    PublicProductList,
    PublicProjectList,
    PublicServiceList,
    PublicSlideList,
    PublicTeamMemberList,
    PublicTestimonialList,
)
from .views import (
    AdminInquiryDetail,
    AdminInquiryList,
    AdminPortfolioDownload,
    AdminUserList,
    ContactView,
    DashboardView,
    HealthView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("auth/csrf/", CsrfView.as_view(), name="auth-csrf"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("slides/", PublicSlideList.as_view(), name="slides"),
    path("projects/", PublicProjectList.as_view(), name="projects"),
    path("services/", PublicServiceList.as_view(), name="services"),
    path("team/", PublicTeamMemberList.as_view(), name="team"),
    path("testimonials/", PublicTestimonialList.as_view(), name="testimonials"),
    path("faqs/", PublicFAQList.as_view(), name="faqs"),
    path("products/", PublicProductList.as_view(), name="products"),
    path("departments/", PublicDepartmentList.as_view(), name="departments"),
    path("clients/", PublicClientList.as_view(), name="clients"),
    path("homepage/", PublicHomepage.as_view(), name="homepage"),
    path("admin/dashboard/", DashboardView.as_view(), name="admin-dashboard"),
    path("admin/portfolio/", AdminPortfolioDownload.as_view(), name="admin-portfolio"),
    path("admin/inquiries/", AdminInquiryList.as_view(), name="admin-inquiries"),
    path(
        "admin/inquiries/<int:pk>/",
        AdminInquiryDetail.as_view(),
        name="admin-inquiry-detail",
    ),
    path("admin/users/", AdminUserList.as_view(), name="admin-users"),
    path("admin/slides/", AdminSlideListCreate.as_view(), name="admin-slides"),
    path("admin/slides/<int:pk>/", AdminSlideDetail.as_view(), name="admin-slide-detail"),
    path("admin/projects/", AdminProjectListCreate.as_view(), name="admin-projects"),
    path(
        "admin/projects/<int:pk>/",
        AdminProjectDetail.as_view(),
        name="admin-project-detail",
    ),
    path("admin/services/", AdminServiceListCreate.as_view(), name="admin-services"),
    path(
        "admin/services/<int:pk>/",
        AdminServiceDetail.as_view(),
        name="admin-service-detail",
    ),
    path("admin/team/", AdminTeamMemberListCreate.as_view(), name="admin-team"),
    path(
        "admin/team/<int:pk>/",
        AdminTeamMemberDetail.as_view(),
        name="admin-team-detail",
    ),
    path(
        "admin/testimonials/",
        AdminTestimonialListCreate.as_view(),
        name="admin-testimonials",
    ),
    path(
        "admin/testimonials/<int:pk>/",
        AdminTestimonialDetail.as_view(),
        name="admin-testimonial-detail",
    ),
    path("admin/faqs/", AdminFAQListCreate.as_view(), name="admin-faqs"),
    path("admin/faqs/<int:pk>/", AdminFAQDetail.as_view(), name="admin-faq-detail"),
    path("admin/products/", AdminProductListCreate.as_view(), name="admin-products"),
    path(
        "admin/products/<int:pk>/",
        AdminProductDetail.as_view(),
        name="admin-product-detail",
    ),
    path(
        "admin/departments/",
        AdminDepartmentListCreate.as_view(),
        name="admin-departments",
    ),
    path(
        "admin/departments/<int:pk>/",
        AdminDepartmentDetail.as_view(),
        name="admin-department-detail",
    ),
    path("admin/clients/", AdminClientListCreate.as_view(), name="admin-clients"),
    path(
        "admin/clients/<int:pk>/",
        AdminClientDetail.as_view(),
        name="admin-client-detail",
    ),
    path("admin/homepage/", AdminHomepage.as_view(), name="admin-homepage"),
    path("admin/media/", AdminMediaListCreate.as_view(), name="admin-media"),
    path("admin/media/<int:pk>/", AdminMediaDetail.as_view(), name="admin-media-detail"),
]
